---
sudo: required

services:
  - docker

language: python
python: "2.7"

matrix:
  include:
    - os: osx
      language: generic
      env:
        - OS=darwin

addons:
  apt:
    packages:
      - python-pip

branches:
  except:
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

env:
  - OS=archlinux_latest
  - OS=centos_7
  - OS=fedora_23
  - OS=fedora_24
  - OS=fedora_25
  - OS=fedora_26
  - OS=fedora_27
  - OS=debian_jessie
  - OS=debian_stretch
  - OS=ubuntu_trusty
  - OS=ubuntu_xenial

before_install:
  - >-
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew upgrade openssl || brew install openssl || true
      brew upgrade python@2 || brew install python@2 || true
      brew upgrade md5sha1sum || brew install md5sha1sum || true
      virtualenv venv -p python
      source venv/bin/activate
      pip install ansible
    fi

install:
  - pip install ansible-galaxy-local-deps dcb==0.0.14
  - ansible-galaxy-local-deps-write
  - >-
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      printf '[defaults]\nroles_path=../' > ansible.cfg
      if [ -f requirements.yml ]; then
        ansible-galaxy install -r requirements.yml
      fi
    fi

script:
  - >-
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    dcb
    --upstreamgroup andrewrothstein
    --upstreamapp docker-ansible-role
    --pull ${OS}
    --write ${OS}
    --build ${OS}
    --push ${OS}
    ;
    fi
  - >-
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      ansible-playbook tests/test.yml -i tests/inventory
    fi
